"""added file_path to snippets

Revision ID: a32aec75cdfd
Revises: f49879b81f0b
Create Date: 2026-06-15 20:46:15.956854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32aec75cdfd'
down_revision: Union[str, Sequence[str], None] = 'f49879b81f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippets', 'file_path')
    # ### end Alembic commands ###
