"""added description to snippets

Revision ID: f49879b81f0b
Revises: 90b8d530bee8
Create Date: 2026-06-15 19:53:15.257215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49879b81f0b'
down_revision: Union[str, Sequence[str], None] = '90b8d530bee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippets', 'description')
    # ### end Alembic commands ###
